### PR TITLE
Fix deprecated call/config

### LINKED ISSUE #8: Workspace.Object.defineProperty.get is deprecated.
Use ::getActivePaneItem() instead of the ::activePaneItem property
```
Workspace.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:892:14)
Object.erb_tags (/Users/goddamnhippie/Code/dotfiles/source/atom/packages/erb-snippets/lib/erb-snippets.coffee:17:28)
```

### LINKED ISSUE #10: Use activationCommands instead of activationEvents in your package.json
erb_snippet

### LINKED ISSUE #11: Deprecated Atom APIs will be removed June 1st
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.5.0`) of this package:

1. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: ```json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] } ```
1. Use ::getActivePaneItem() instead of the ::activePaneItem property

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

### LINKED ISSUE #12: Package.getActivationCommands is deprecated.
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:
```json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```
```
Package.getActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:808:9)
Package.hasActivationCommands (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:733:20)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:185:24)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:177:12)
PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:355:14)
```

### PR DESCRIPTION
**Pull request by beathyate**
Closes #8 
Closes #10 
Closes #11 
Closes #12

### CODE REVIEW

**Comment by tvdeyen** [comment]
@MartinPeverelli please merge this :+1:

**Comment by tvdeyen** [comment]
@goddamnhippie how is possible to install your fork into Atom? Tried to install it manually, but this didn't work for me? How do you installed it?

**Comment by goddamnhippie** [comment]
@tvdeyen you can clone it and use `apm link` I think, but I’ve migrated to this plugin: [rails-snippets](https://atom.io/packages/rails-snippets). It also has other useful snippets.

**Comment by tvdeyen** [comment]
@goddamnhippie thanks! Actually I already had this installed :)

**Comment by lonre** [comment]
@MartinPeverelli please merge this +1

**Pull request closed without merging**
